# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 145ef73bb9bf56f03a444fc51d788d2b5ae994b09bc2d6c1235cc354c816aebc49a35daea9c9c685dc59239ba8a10645850601ebf2ac2ab1e383050b940ff566

test:
  secret_key_base: ac9d0085206759961a0a8dfd165d72171fee00aa15f33d0bc9f148963242e6aa5e476f95cc87729e8ffb7dff7edc50624c3dd54568c93efb63479323ccbb457a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
